# Generated by Django 6.1.1 on 2026-10-06 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=300, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('awaiting_upload', 'Awaiting Upload'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('needs_review', 'Needs Review'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='awaiting_upload', max_length=20)),
                ('collected_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.center')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_code', models.CharField(max_length=20)),
                ('loinc', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('canonical_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('canonical_unit', models.CharField(max_length=30)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('effective_date', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('download', 'Download'), ('list', 'List')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.report')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['patient', '-created_at'], name='reports_rep_patient_0352d5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['center', '-created_at'], name='reports_rep_center__971f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['patient', 'loinc', 'effective_date'], name='reports_obs_patient_1ee79b_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('report', 'marker_code'), name='one_value_per_marker_per_report'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['patient', '-at'], name='reports_acc_patient_fae916_idx'),
        ),
    ]
