# Generated by Django 6.1.1 on 2026-10-06 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='extraction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('download', 'Download'), ('list', 'List'), ('review', 'Review'), ('export', 'Export'), ('erase', 'Erase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
