# Generated by Django 6.1.1 on 2026-10-07 13:59

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_extraction_and_audit_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportShareToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="share_tokens", to="reports.report"
                    ),
                ),
            ],
        ),
    ]
